networks:
  webnet:
    driver: bridge

services:
  app:
    build: ./app
    container_name: app
    environment:
      - NODE_ENV=production
      - APP_BASE_URL=${APP_BASE_URL:-https://app.vpn.local}
      - OIDC_ISSUER=${OIDC_ISSUER:-https://sso.vpn.local/realms/demo}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID:-web-app}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET:-changeme}
      - SESSION_SECRET=${SESSION_SECRET:-please_change_me}
    expose:
      - "3000"                   # доступно только внутри сети webnet
    networks: [webnet]
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/keycloak/init:/opt/keycloak/data/import:ro
    expose:
      - "8080"
    networks: [webnet]
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - app
      - keycloak
    networks: [webnet]
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infra/nginx/tls:/etc/nginx/tls:ro
    # Публикуем ТОЛЬКО на IP wg0 (10.6.0.1)
    ports:
      - "10.6.0.1:443:443"      # app.vpn.local
      - "10.6.0.1:8443:8443"    # sso.vpn.local
    restart: unless-stopped
